
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: localhost
  password: <%= ENV['POSTGRESQL_PASSWORD'] || '' %>

development:
  <<: *default
  database: rspotify_development

test:
  <<: *default
  username: <%= ENV['TEST_POSTGRES_USER'] %>
  password: <%= ENV['TEST_POSTGRES_PASS'] %>
  database: rspotify_test

staging:
  <<: *default
  database: rspotify_staging
  username: <%= ENV['STAGING_POSTGRES_USER'] %>
  password: <%= ENV['STAGING_POSTGRES_PASS'] %>
  port: 5433
  host: localhost

production:
  <<: *default
  database: rspotify_production
  username: <%= ENV['PRODUCTION_POSTGRES_USER'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASS'] %>
  port: 5432
  host: <%= ENV['PRODUCTION_POSTGRES_HOST'] %>
